---
hibernate:
    cache:
        queries: true
        use_second_level_cache: true
        use_query_cache: true
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    # driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # driverClassName: org.postgresql.Driver
    username: lms
    password: 8FTeR5dA!
    # username: loan-190
    # password: g8j~eWqb3ovigrLz

environments:
    development:
        dataSource:
            dbCreate: update
            # url: jdbc:sqlserver://10.0.8.240:1433;DatabaseName=lmsstaging
            # url: jdbc:sqlserver://10.0.8.240:1433;DatabaseName=lms_test
            url: jdbc:sqlserver://10.0.8.240:1433;DatabaseName=lms_test
            # url: jdbc:mysql://localhost:3306/loan-160?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
            # url: jdbc:mysql://10.0.8.151:3306/lms1?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
            # url: jdbc:postgresql://127.0.0.1:5432/lms
    test:
        dataSource:
            dbCreate: create-drop
            url: jdbc:mysql://localhost:3306/loan-160?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    production:
        dataSource:
            dbCreate: update
            # product
            # url: jdbc:mysql://10.0.8.153:3306/lms?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
            # url: jdbc:sqlserver://10.0.8.241:1433;DatabaseName=lms
            url: jdbc:sqlserver://10.0.8.240:1433;DatabaseName=lms_test
            # url: jdbc:sqlserver://10.0.8.240:1433;DatabaseName=lmsstaging
            # url: jdbc:sqlserver://10.0.8.240:1433;DatabaseName=lms_data
            # url: jdbc:sqlserver://10.0.8.240:1433;DatabaseName=lms_ceshi
            properties:
                jmxEnabled: true
                initialSize: 50
                maxActive: 500
                minIdle: 20
                maxIdle: 300
                maxWait: 120000
                maxAge:  600000
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: SELECT 1
                validationQueryTimeout: 60
                validationInterval: 30000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    profile: web
    codegen:
        defaultPackage: com.next
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 104857600
            maxRequestSize: 104857600
    converters:
        encoding: UTF-8
        json:
          default:
            deep: true
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    mail:
              encoding: UTF-8
              host: 'smtp.exmail.qq.com'
              port: 465
              username: 'lms@zhongjiaxin.com'
              password: '1lgh6gQ6qD1Sd2hz'
              props:
                    'mail.smtp.port': 465
                    'mail.smtp.auth': true
                    'mail.smtp.starttls.enable': true
                    'mail.smtp.socketFactory.port': 465
                    'mail.smtp.socketFactory.class': 'javax.net.ssl.SSLSocketFactory'
                    'mail.smtp.socketFactory.fallback': true
              default:
                      from: 'lms@zhongjiaxin.com'
endpoints:
    jmx:
        unique-names: true
